# Generated by Django 6.0.5 on 2026-07-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
            ],
        ),
    ]
