# Generated by Django 6.0.5 on 2026-07-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_role_customeuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
    ]
